[env]
TERM = "xterm-256color"

[window]
padding.x = 3
padding.y = 3

#decorations = "buttonless" # No Mac buttons, rounded corners
decorations = "none"        # No Mac buttons, square corners

opacity = 1.0
blur = false

option_as_alt = "Both"

[font]
normal.family = "BitstromWera Nerd Font Mono"
size = 12
