# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":currentdate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # For Resume Submissions
  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/gallaghergreg/"

  - trigger: ":myemail"
    replace: "greg.b.gallagher@gmail.com"

  # For Logseq
  - trigger: ":ppc"
    replace: "status:: #submitted\nposition:: \nlocation:: \nwebsite:: https://example.com\ncontact:: \nlast-update:: \nnext-update:: \nsummary:: \n"

  - trigger: ":ppp"
    replace: "e-mail:: \ncompany:: [[Company]]\nposition:: \nlinkedin:: \nphone:: \nlocation:: \nbirthdate:: \nsignificant-other:: \nchildren:: \nrecord-created:: [[{{logseq_today}}]]\n"
    vars:
      - name: logseq_today
        type: date
        params:
          format: "%F"
      
  # And much more! For more information, visit the docs: https://espanso.org/docs/
